#!/bin/bash

source "${TESTRAIL_API_SOURCE}/cli/output.sh"

_request() {
  local url="${TESTRAIL_API_URL}/index.php?/api/v2/${1:?Endpoint is required}"
  local curl_argv=("${@:2}")
  local credential="$TESTRAIL_API_USER:$TESTRAIL_API_KEY"
  local response
  local api_error

  response=$(curl -s \
    -H 'Content-Type: application/json' \
    -u "$credential" \
    "$url" \
    "${curl_argv[@]}") \
  || ERROR "Curl return code is $? for command:\n"  \
  || return $?

  api_error=$(jq -r 'if type =="object" and has("error") then .error else empty end' <<< "$response") \
  && test ! "$api_error" \
  || ERROR 'TestRail API returns error:\n' "$api_error" \
  || return $?

  jq -c '.' <<< "$response" \
  || ERROR "Response is not a json:" "$response" \
  || return $?
}

get_case() {
  local id=${1:?Case ID is required}
  _request "get_case/${id}" \
  || ERROR "Couldn't get case with ID $id"
  return $?
}

update_case() {
  local id=${1:?Case ID is required}
  local case_json=${2:?Test case is required}
  _request "update_case/${id}" -X POST -d "$case_json" \
  || ERROR "Couldn't update case with ID $id:\n" "$case_json" \
  || return $?
}

get_test() {
  local test_id=${1:?Test ID is required}
  _request "get_test/${test_id}" \
  || ERROR "Couldn't get test with ID $test_id" \
  || return $?
}

get_cases_from_section() {
  local project=${1:?Project ID is required}
  local suite=${2:?Suite ID is required}
  local section_id=${3:?Section ID is required}
  _request "get_cases/${project}&suite_id=${suite}&section_id=${section_id}" \
  || ERROR "Couldn't get cases for section ID $section_id" \
  || return $?
}

get_results() {
  local test=${1:?Test ID is required}
  _request "get_results/${test}" \
  || ERROR "Couldn't get result for test $test" \
  || return $?
}

get_results_for_run() {
  local run_id=${1:?Run ID is required}
  _request "get_results_for_run/${run_id}" \
  || ERROR "Couldn't get result for run $run_id" \
  || return $?
}

get_results_for_case() {
  local run=${1:?Run ID is required}
  local case=${2:?Case ID is required}
  _request "get_results_for_case/${run}/${case}" \
  || ERROR "Couldn't get results for run $run and case $case" \
  || return $?
}

get_suite() {
  local suite_id=${1:?Suite ID is required}
  _request "get_suite/${suite_id}" \
  || ERROR "Couldn't get suite $suite_id" \
  || return $?
}

get_section() {
  local section_id=${1:?Section ID is required}
  _request "get_section/${section_id}" \
  || ERROR "Couldn't get section $section_id" \
  || return $?
}

get_sections() {
  local project=${1:?Project ID is required}
  local suite=${2:?Suite ID is required}
  _request "get_sections/${project}&suite_id=${suite}" \
  || ERROR "Couldn't get sections for $project project and $suite suite" \
  || return $?
}

update_section() {
  local id=${1:?Section ID is required}
  local body=${2:?Section body is required}
  _request "update_section/${id}" -X POST -d "$body" \
  || ERROR "Couldn't update section with ID $id" \
  || return $?
}

delete_section() {
  local id=${1:?Section ID is required}
  _request "delete_section/${id}" -X POST \
  || ERROR "Couldn't update section with ID $id" \
  || return $?
}

eval "$*"
