#!/bin/bash
source "${TESTRAIL_API_SOURCE}/cli/output.sh"

section_id=${1:?Section ID is required}

backup_dir="$(realpath)/${section_id}_backup_$(date "+%Y-%m-%d_%H:%M:%S")"

get_nested_cases "$section_id" | parallel -n1 -I% -r -P"$TESTRAIL_API_THREAD" backup_case % "$backup_dir" \
&& INFO "$backup_dir"