#!/bin/bash
source "${TESTRAIL_API_SOURCE}/cli/output.sh"

project=${1:?Project ID is required}
suite=${2:?Suite ID is required}
section_name="${3:?Parent section name required}"
rc=0

section_ids=("$(get_sections "$project" "$suite" | jq -M ".[] | select(.name == \"$section_name\") | .id")")
section_ids_count="$(wc -w <<< "${section_ids[@]}")"

test "$section_ids_count" -eq 0 \
&& ERROR "No section with name '$section_name'" \
&& exit 1

echo "${section_ids[@]}"

test "$section_ids_count" -gt 1 \
&& WARNING "Found multiple sections with name '$section_name'" \
&& rc=2

exit "$rc"
