#!/bin/bash
source "${TESTRAIL_API_SOURCE}/cli/output.sh"

sections_ids=("${@}")

sections_ids+=("$(read_stdin)")

parallel -n1 -I% -d" " -r -P"$TESTRAIL_API_THREAD" tr_api get_section % ::: "${sections_ids[*]}" \
| jq -s | jq -c 'select(length > 0)'